version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: tasks
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    restart: unless-stopped
    networks:
      - backend
# BACKEND*****************************************
  springbootapp:
    image: akhilmangala/task-management:latest
    container_name: taskmanagement
    expose:
      - 8080
    ports:
      - 8081:8080
    # env_file:
    #   - ./backend/task-management/task-management.env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=tasks
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

      - API_IDENTIFIER=https://bootcamp-todo-user.us.auth0.com/api/v2/
      - ISSUER_URI=https://bootcamp-todo-user.us.auth0.com/
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - backend
# FRONTEND*****************************************
  frontend:
    image: akhilmangala/todo-react:latest
    ports:
      - "3000:80"
    # env_file:
    #   - ./web-ui/.env
    environment:
      - REACT_APP_BACKEND_HOST=http://localhost:8080
    networks:
      - frontend
volumes:
  postgres-data:
networks:
  backend:
  frontend:
