pipeline {
    agent any
    environment {
            registry = "docker.pkg.github.com/akhilanilm/todo-app-jenkins/task-management"
            registryCredential = 'github-registry'
            dockerImage=''
          }
    stages {
        stage('Setup') {
            steps {
                checkout scm
                // sh "cd bootcamp4-todo && docker-compose up -d"
                // sh "cd bootcamp4-todo/web-ui/ && npm install"
            }
        }
        stage('Test') {
             environment {
                    POSTGRES_HOST = "localhost"
                    POSTGRES_PORT = "5432"
                    POSTGRES_DB = "tasks"
                    POSTGRES_USER = "admin"
                    POSTGRES_PASSWORD = "admin"
                    API_IDENTIFIER = "https://bootcamp-todo-user.us.auth0.com/api/v2/"
                    ISSUER_URI = "https://bootcamp-todo-user.us.auth0.com/"
                }
            steps {
                sh "pwd && ls"
                // sh "cd bootcamp4-todo/backend/task-management && mvn test"
                // sh "cd bootcamp4-todo/web-ui/ && npm run test"
            }
        }
        stage('Building Docker Image') {
              steps{
              dir("bootcamp4-todo/backend/task-management"){
              script {
                         dockerImage = docker.build registry + ":$BUILD_NUMBER"
                       }
              }
              }
            }
        stage('Deploy Docker Image to Dockerhub') {
            steps{
            sh 'echo ${GH_TOKEN} | docker login docker.pkg.github.com -u akhilanilm --password-stdin'
            sh 'docker push '+registry+":$BUILD_NUMBER"
            }
        }
    }
}